### ISSUE TITLE
Default rendering shows /header.plain.html and /footer.plain.html

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pages#24]
Easy to reproduce, load any repo with helix-pages (like https://helix-templates-content-kptdobe.project-helix.page/)

If no header.md and/or footer.md is found in the repo, the ESI includes fails and the path to the request is returned.

Solution / workaround is being tracked as part of https://github.com/adobe/helix-publish/issues/83

**Comment by trieloff** [comment]
You might be able to hide the error text like this:

```css
footer {
  color: gray; /* same as background */
}
footer * {
  color: black;
}
```
