### ISSUE TITLE
embed wrapping: add full tree

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pages#428]
For theblog project, internal embeds would be stored in a more complex structure than just `parent/embed.html`. See https://github.com/adobe/theblog/issues/377.. It could potentially be something like `root/x/.../z/parent/embed.html`.

Today, only the `parent` folder is added as a class while the need for global styling is on the `root` folder or the `x` folder in the case of the blog.

Proposal here is to add a class per parent in the path. For path `root/x/y/z/parent/embed.html` which would lead to add classes: `embed-internal-root`, `embed-internal-x`, `embed-internal-y`, `embed-internal-z`, `embed-internal-parent` instead of just `embed-internal-parent`

This would allow to create css rules like `.embed-internal-root.embed-internal-x` to style all embeds coming from a specific folder.

This is a lot of classes but only solution to not have to change the code each time someone creates a new subfolder.

cc @trieloff @davidnuescheler @rofe

**Comment by kptdobe** [comment]
I have found a complete different approach to solve this styling issue which also would invalidate what has been done in https://github.com/adobe/helix-pages/issues/408: use `helix-markup.yaml`!

The styling of embed is project specific and "embed" specific. For that, we can use `helix-markup.yaml` to define the rule of classes to apply on the embeds, depending for example of the page type or the path of the page. Example:

```yaml
version: 1
markup:
  promotions:
    match: /(|:lang/promotions/)(.*)(.embed.html)
    type: url
    classnames: embed-internal-promotions
```

With one minor change in helix-pages, this would add the `embed-internal-promotions` style to all pages under `/en/promotions` and for the selector `.embed`.

```yaml
version: 1
markup:
  copyright:
    match: /components/copyright.embed.html
    type: url
    classnames: embed-internal-copyright
```

This would add `embed-internal-copyright` class to the copyright embeds.

@davidnuescheler @trieloff WDYT ?
